### ISSUE TITLE
Rust Bindings Generator Ignores/Skips Defined Types

### ISSUE THREAD

**Issue by theduke** [wasmerio/wai#24]
When generating Rust bindings with the below `.wit` file at least one (probably several) types are not actually being generated.

The one that is definitely skipped is `record prestat-u-dir`.

[output.wit.txt](https://github.com/wasmerio/wai/files/10185901/output.wit.txt)

**Comment by Michael-F-Bryan** [comment]
@theduke, this was fixed in #20. You need to set [the `force_generate_structs` option](https://github.com/wasmerio/wai/blob/e8f71ad2232c8da4081ec349179d72a0982c73df/crates/gen-rust-wasm/src/lib.rs#L59-L61) if using `wai-bindgen-gen-rust` as a crate or pass the `--force-generate-structs` flag.

**Comment by theduke** [comment]
Problem was that the fix was not published on crates.io yet.
